[package]
name = "tf-plugin"
version = "0.1.0"
edition = "2021"
authors = ["Alix Bott <bott.alix@gmail.com>"]
description = "Interface for Tunefire plugins"
license = "MIT"


[dependencies]
anyhow = "1.0.68"
druid = { workspace = true }
url = "2.3.1"
tf-player = { path = "../tf-player" }
